# Generated by Django 5.0.2 on 2024-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P09Film',
            fields=[
                ('idfilm', models.AutoField(db_column='idFilm', primary_key=True, serialize=False)),
                ('titrefilm', models.CharField(db_column='titreFilm', max_length=140)),
                ('paysfilm', models.CharField(blank=True, db_column='paysFilm', max_length=60, null=True)),
                ('idrealisateur', models.IntegerField(db_column='idRealisateur')),
            ],
            options={
                'db_table': 'p09_film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P09Laureat',
            fields=[
                ('idlaureat', models.AutoField(db_column='idLaureat', primary_key=True, serialize=False)),
                ('nomlaureat', models.CharField(db_column='nomLaureat', max_length=91)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('pays', models.CharField(blank=True, max_length=60, null=True)),
                ('metier', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'p09_laureat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P09Prix',
            fields=[
                ('idprix', models.AutoField(db_column='idPrix', primary_key=True, serialize=False)),
                ('nomprix', models.CharField(db_column='nomPriX', max_length=91)),
                ('typeprix', models.CharField(blank=True, db_column='typePrix', max_length=50, null=True)),
            ],
            options={
                'db_table': 'p09_prix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P09Recompenserfilm',
            fields=[
                ('idfilm', models.IntegerField(db_column='idFilm', primary_key=True, serialize=False)),
                ('idprix', models.IntegerField(db_column='idPrix')),
                ('editionprixf', models.DateField(blank=True, db_column='editionPrixF', null=True)),
            ],
            options={
                'db_table': 'p09_recompenserfilm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P09Recompenserlaureat',
            fields=[
                ('idlaureat', models.IntegerField(db_column='idLaureat', primary_key=True, serialize=False)),
                ('idprix', models.IntegerField(db_column='idPrix')),
                ('editionprixl', models.DateField(blank=True, db_column='EditionPrixL', null=True)),
            ],
            options={
                'db_table': 'p09_recompenserlaureat',
                'managed': False,
            },
        ),
    ]
